# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x04gnss\"_\n\x0eServerResponse\x12/\n\x0flocation_update\x18\x01 \x01(\x0b\x32\x14.gnss.LocationUpdateH\x00\x12\x10\n\x06status\x18\x02 \x01(\tH\x00\x42\n\n\x08response\"\x95\x02\n\x0eLocationUpdate\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x01\x12\x10\n\x08\x61\x63\x63uracy\x18\x05 \x01(\x02\x12\x0f\n\x07\x62\x65\x61ring\x18\x06 \x01(\x02\x12\r\n\x05speed\x18\x07 \x01(\x02\x12\x12\n\nsatellites\x18\x08 \x01(\x05\x12\x10\n\x08provider\x18\t \x01(\t\x12\x14\n\x0clocation_age\x18\n \x01(\x02\x12\x19\n\x11vertical_accuracy\x18\x0b \x01(\x02\x12\x18\n\x10\x62\x65\x61ring_accuracy\x18\x0c \x01(\x02\x12\x16\n\x0espeed_accuracy\x18\r \x01(\x02\x42%\n\x14\x64\x65zz.gnssshare.protoB\rLocationProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024dezz.gnssshare.protoB\rLocationProto'
  _globals['_SERVERRESPONSE']._serialized_start=24
  _globals['_SERVERRESPONSE']._serialized_end=119
  _globals['_LOCATIONUPDATE']._serialized_start=122
  _globals['_LOCATIONUPDATE']._serialized_end=399
# @@protoc_insertion_point(module_scope)
