#!/usr/bin/env python3
"""
Gzip static HTML assets and embed them into the firmware.

Generates:
  - lib/ElegantOTA/src/elop.cpp / elop.h (OTA page)
  - src/web_index.cpp / include/web_index.h (main page)
  - src/web_portal.cpp / include/web_portal.h (Wi-Fi portal)

Runs automatically before PlatformIO build (pre:buildprog) and can be run
manually via `python tools/embed_assets.py`.
"""

from io import BytesIO
from pathlib import Path
import gzip

try:
  from SCons.Script import Import

  Import("env")  # type: ignore
except Exception:
  env = None  # Running outside PlatformIO


def _project_dir() -> Path:
  if env and env.get("PROJECT_DIR"):
    return Path(env["PROJECT_DIR"])
  try:
    return Path(__file__).resolve().parents[1]
  except NameError:
    return Path.cwd()


PROJECT_DIR = _project_dir()

ASSETS = [
    {
        "name": "WEB_INDEX_HTML",
        "input": PROJECT_DIR / "lib/WebUI/index.html",
        "cpp": PROJECT_DIR / "src/web_index.cpp",
        "header": PROJECT_DIR / "include/web_index.h",
        "guard": "web_index_h",
    },
    {
        "name": "WEB_PORTAL_HTML",
        "input": PROJECT_DIR / "lib/WebUI/portal.html",
        "cpp": PROJECT_DIR / "src/web_portal.cpp",
        "header": PROJECT_DIR / "include/web_portal.h",
        "guard": "web_portal_h",
    },
]


def gzip_bytes(data: bytes) -> bytes:
  buf = BytesIO()
  with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
    gz.write(data)
  return buf.getvalue()


def format_array(data: bytes) -> str:
  lines = []
  for i in range(0, len(data), 20):
    chunk = ", ".join(str(b) for b in data[i:i + 20])
    lines.append(f"  {chunk}")
  return ",\n".join(lines)


def write_cpp(symbol: str, header: Path, cpp: Path, data: bytes) -> None:
  body = format_array(data)
  cpp.parent.mkdir(parents=True, exist_ok=True)
  content = (
      f'#include "{header.name}"\n\n'
      "// Auto-generated by tools/embed_assets.py. Do not edit manually.\n\n"
      f"const uint8_t {symbol}[{len(data)}] PROGMEM = {{\n{body}\n}};\n"
  )
  cpp.write_text(content)


def write_header(symbol: str, guard: str, length: int, header: Path) -> None:
  header.parent.mkdir(parents=True, exist_ok=True)
  content = (
      f"#ifndef {guard}\n"
      f"#define {guard}\n\n"
      "#include <Arduino.h>\n\n"
      f"extern const uint8_t {symbol}[{length}];\n\n"
      "#endif\n"
  )
  header.write_text(content)


def generate(*_, **__) -> None:
  for asset in ASSETS:
    input_path: Path = asset["input"]
    cpp_path: Path = asset["cpp"]
    header_path: Path = asset["header"]
    symbol: str = asset["name"]
    guard: str = asset["guard"]

    if not input_path.exists():
      print(f"[embed] Skipping missing asset: {input_path}")
      continue

    data = gzip_bytes(input_path.read_bytes())
    write_cpp(symbol, header_path, cpp_path, data)
    write_header(symbol, guard, len(data), header_path)

    print(
        f"[embed] {len(data)} bytes from {input_path.relative_to(PROJECT_DIR)} -> {cpp_path.relative_to(PROJECT_DIR)}"
    )


if env:
  env.AddPreAction("buildprog", generate)
elif __name__ == "__main__":
  generate()
