#!/usr/bin/env python3
"""
Generate a monotonically increasing build version based on UTC time.

Outputs include/build_version.h with macros BUILD_VERSION and BUILD_TIMESTAMP.
Runs automatically before PlatformIO build (pre:buildprog) and can be invoked
manually with `python tools/generate_build_version.py`.
"""

from datetime import datetime, timezone
from pathlib import Path

try:
  from SCons.Script import Import

  Import("env")  # type: ignore
except Exception:
  env = None  # Running outside PlatformIO


def _project_dir() -> Path:
  if env and env.get("PROJECT_DIR"):
    return Path(env["PROJECT_DIR"])
  try:
    return Path(__file__).resolve().parents[1]
  except NameError:
    return Path.cwd()


PROJECT_DIR = _project_dir()
HEADER_PATH = PROJECT_DIR / "include" / "build_version.h"


def ensure_header_dir():
  HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)


def current_version():
  now = datetime.now(timezone.utc)
  version = now.strftime("%Y%m%d%H%M%S")
  timestamp = now.strftime("%Y-%m-%dT%H:%M:%SZ")
  return version, timestamp


def write_header(version: str, timestamp: str) -> None:
  ensure_header_dir()
  content = (
      "// Auto-generated by tools/generate_build_version.py. Do not edit manually.\n"
      "#pragma once\n\n"
      f"#define BUILD_VERSION \"{version}\"\n"
      f"#define BUILD_TIMESTAMP \"{timestamp}\"\n"
  )
  HEADER_PATH.write_text(content)


def generate(*_, **__) -> None:
  version, timestamp = current_version()
  write_header(version, timestamp)
  relative = HEADER_PATH.relative_to(PROJECT_DIR)
  print(f"[build version] {version} ({timestamp}) -> {relative}")


if env:
  env.AddPreAction("buildprog", generate)
elif __name__ == "__main__":
  generate()
